/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bugs;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void repeatSeparatorSolution1() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.repeatSeparator("Word", "X", 3), "WordXWordXWord");
    }

    @Test
    void repeatSeparatorSolution2() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.repeatSeparator("This", "And", 2), "ThisAndThis");
    }

    @Test
    void repeatSeparatorSolution3() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.repeatSeparator("This", "And", 1), "This");
    }
}
