/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bugs;

public class App {
    // https://codingbat.com/prob/p109637
    // Given two strings, word and a separator sep, return a big string made of
    // count occurrences of the word, separated by the separator string.
    // repeatSeparator("Word", "X", 3) → "WordXWordXWord"
    // repeatSeparator("This", "And", 2) → "ThisAndThis"
    // repeatSeparator("This", "And", 1) → "This"
    public String repeatSeparator(String word, char sep, int count) {
        String returnStr = "";
        for (int i = 1; i < count; i++) {
            if (i == count - 1) {
                returnStr = returnStr + word;
            } else {
                returnStr = returnStr + sep;
            }
        }
        return returnStr;
    }
}
